default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: grit_development

test:
  <<: *default
  database: grit_test

staging:
  <<: *default
  database: grit_staging

production:
  <<: *default
  database: grit_production